version: '3.7'

services:

  json-server:
    build: .
    image: flaviostutz/json-server
    ports:
      - "3000:3000"
    environment:
      - COLLECTIONS=testa,testb,testc,testd,teste
      - RESPONSE_DELAY_MS=400
